CREATE TABLE IF NOT EXISTS MEIODETRANSPORTE(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DESCRICAO VARCHAR,
    TIPO VARCHAR
);

CREATE TABLE IF NOT EXISTS EVENTO(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    MEIODETRANSPORTE_ID INTEGER,
    DATA DATETIME,
    FOREIGN KEY (MEIODETRANSPORTE_ID) REFERENCES MEIODETRANSPORTE(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS VIAGEM(
    EVENTO_ID INTEGER PRIMARY KEY,
    INICIO DATETIME,
    FIM DATETIME,
    DISTANCIA FLOAT,
    FOREIGN KEY (EVENTO_ID) REFERENCES EVENTO(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS GASTO(
    EVENTO_ID INTEGER PRIMARY KEY,
    TIPO INTEGER NOT NULL,
    VALOR NUMERIC,
    OBSERVACAO VARCHAR,
    FOREIGN KEY (EVENTO_ID) REFERENCES EVENTO(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ALUGADO(
    MEIODETRANSPORTE_ID INTEGER PRIMARY KEY,
    LOCADORA VARCHAR,
    MARCA VARCHAR,
    MODELO VARCHAR,
    COR VARCHAR,
    FOREIGN KEY (MEIODETRANSPORTE_ID) REFERENCES MEIODETRANSPORTE(ID)
);

CREATE TABLE IF NOT EXISTS COMPARTILHADO(
    MEIODETRANSPORTE_ID INTEGER PRIMARY KEY,
    EMPRESA VARCHAR,
    FOREIGN KEY (MEIODETRANSPORTE_ID) REFERENCES MEIODETRANSPORTE(ID)
);

CREATE TABLE IF NOT EXISTS PUBLICO(
    MEIODETRANSPORTE_ID INTEGER PRIMARY KEY,
    EMPRESA VARCHAR,
    FOREIGN KEY (MEIODETRANSPORTE_ID) REFERENCES MEIODETRANSPORTE(ID)
);

CREATE TABLE IF NOT EXISTS PARTICULAR(
    MEIODETRANSPORTE_ID INTEGER PRIMARY KEY,
    MARCA VARCHAR,
    MODELO VARCHAR,
    COR VARCHAR,
    FOREIGN KEY (MEIODETRANSPORTE_ID) REFERENCES MEIODETRANSPORTE(ID)
);

CREATE TABLE IF NOT EXISTS USUARIO(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME VARCHAR NOT NULL,
    SOBRENOME VARCHAR NOT NULL,
    EMAIL VARCHAR NOT NULL,
    SENHA VARCHAR NOT NULL,
    FACEBOOK VARCHAR,
    SINCRONIZAR BOOLEAN NOT NULL,
    LASTLOGIN DATETIME
);

CREATE TABLE IF NOT EXISTS USUARIO_HAS_MEIODETRANSPORTE(
    USUARIO_ID INTEGER,
    MEIODETRANSPORTE_ID INTEGER,
    PRIMARY KEY (USUARIO_ID, MEIODETRANSPORTE_ID),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID) ON DELETE CASCADE,
    FOREIGN KEY (MEIODETRANSPORTE_ID) REFERENCES MEIODETRANSPORTE(ID) ON DELETE CASCADE
);