SELECT A.ID
,A.DATA
,A.TIPO
,A.VALOR
,A.OBSERVACAO
,B.ID AS MEIODETRANSPORTE_ID
,B.CATEGORIA AS CATEGORIA
 FROM (SELECT E.ID
        , E.DATA
        , G.TIPO
        , G.VALOR
        , G.OBSERVACAO
        , E.MEIODETRANSPORTE_ID
            FROM GASTO G INNER JOIN EVENTO E
                ON G.EVENTO_ID = E.ID
                WHERE E.DATA BETWEEN ? AND ?) A
      INNER JOIN (
        SELECT M.ID AS ID
            ,'Alugado' AS CATEGORIA
        FROM ALUGADO AL INNER JOIN MEIODETRANSPORTE M ON AL.MEIODETRANSPORTE_ID = M.ID
        UNION
        SELECT M2.ID AS ID
            ,'Público' AS CATEGORIA
        FROM PUBLICO PU INNER JOIN MEIODETRANSPORTE M2 ON PU.MEIODETRANSPORTE_ID = M2.ID
        UNION
        SELECT M3.ID AS ID
            ,'Particular' AS CATEGORIA
        FROM PARTICULAR PR INNER JOIN MEIODETRANSPORTE M3 ON PR.MEIODETRANSPORTE_ID = M3.ID
        UNION
        SELECT M4.ID AS ID
            ,'Compartilhado' AS CATEGORIA
        FROM COMPARTILHADO CO INNER JOIN MEIODETRANSPORTE M4 ON CO.MEIODETRANSPORTE_ID = M4.ID
      ) B ON A.MEIODETRANSPORTE_ID = B.ID