SELECT A.ID
,A.DATA
,A.TIPO
,A.VALOR
,A.OBSERVACAO
,M.ID AS MEIODETRANSPORTE_ID
,M.TIPO AS MEIODETRANSPORTE_TIPO
FROM (SELECT E.ID
        , E.DATA
        , G.TIPO
        , G.VALOR
        , G.OBSERVACAO
        , E,MEIODETRANSPORTE_ID
            FROM GASTO G INNER JOIN EVENTO E
                ON G.EVENTO_ID = E.ID
                WHERE E.DATA BETWEEN ? AND ?) A
      INNER JOIN MEIODETRANSPORTE M
        ON A.MEIODETRANSPORTE_ID = M.ID